stages:
  load_data:
    cmd: python src\load_data.py --config=params.yaml
    deps:
    - src\get_data.py
    - src\load_data.py
    - data_given\winequalityN.csv
    outs:
    - data\raw\winequality.csv

  split_data:
    cmd: python src\split_data.py --config=params.yaml
    deps:
    - data\raw\winequality.csv
    - src\split_data.py
    outs:
    - data\processed\train_winequality.csv
    - data\processed\test_winequality.csv

  train_model:
    cmd: python src\train_model.py --config=params.yaml
    deps:
    - data\processed\train_winequality.csv
    - data\processed\test_winequality.csv
    - src\train_model.py
    params:
    - estimators.ElasticNet.params.l1_ratio
    - estimators.ElasticNet.params.alpha
    metrics:
    - report\scores.json:
        cache: false
    - report\params.json:
        cache: false
    outs:
    - save_models\model.joblib